services:
  - type: web
    name: watchtogtr-backend
    env: node
    region: singapore
    plan: free
    root: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
