services:
  - type: web
    name: watchtogtr-backend
    env: node
    region: singapore
    plan: free
    buildCommand: apt-get update && apt-get install -y ffmpeg && cd backend && npm install && npm run build
    startCommand: cd backend && node dist/index.js
    # Install FFmpeg for MKV transcoding
    disk:
      name: ffmpeg-cache
      mountPath: /opt/render/.cache
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
